/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import java.io.IOException
import okhttp3.OkHttpClient
import okhttp3.HttpUrl

import org.openapitools.client.models.ApiResponseBookmarkState
import org.openapitools.client.models.ApiResponseCharacter
import org.openapitools.client.models.ApiResponseLikeState
import org.openapitools.client.models.ApiResponsePageCharacter
import org.openapitools.client.models.Character
import org.openapitools.client.models.HTTPValidationError
import org.openapitools.client.models.ModelApiResponse

import com.squareup.moshi.Json

import org.openapitools.client.infrastructure.ApiClient
import org.openapitools.client.infrastructure.ApiResponse
import org.openapitools.client.infrastructure.ClientException
import org.openapitools.client.infrastructure.ClientError
import org.openapitools.client.infrastructure.ServerException
import org.openapitools.client.infrastructure.ServerError
import org.openapitools.client.infrastructure.MultiValueMap
import org.openapitools.client.infrastructure.PartConfig
import org.openapitools.client.infrastructure.RequestConfig
import org.openapitools.client.infrastructure.RequestMethod
import org.openapitools.client.infrastructure.ResponseType
import org.openapitools.client.infrastructure.Success
import org.openapitools.client.infrastructure.toMultiValue

class CharactersApi(basePath: kotlin.String = defaultBasePath, client: OkHttpClient = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost")
        }
    }

    /**
     * Bookmark Character
     * 
     * @param characterId 
     * @return ApiResponseBookmarkState
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun bookmarkCharacterApiV1CharactersCharacterIdBookmarkPost(characterId: java.util.UUID) : ApiResponseBookmarkState {
        val localVarResponse = bookmarkCharacterApiV1CharactersCharacterIdBookmarkPostWithHttpInfo(characterId = characterId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ApiResponseBookmarkState
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Bookmark Character
     * 
     * @param characterId 
     * @return ApiResponse<ApiResponseBookmarkState?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun bookmarkCharacterApiV1CharactersCharacterIdBookmarkPostWithHttpInfo(characterId: java.util.UUID) : ApiResponse<ApiResponseBookmarkState?> {
        val localVariableConfig = bookmarkCharacterApiV1CharactersCharacterIdBookmarkPostRequestConfig(characterId = characterId)

        return request<Unit, ApiResponseBookmarkState>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation bookmarkCharacterApiV1CharactersCharacterIdBookmarkPost
     *
     * @param characterId 
     * @return RequestConfig
     */
    fun bookmarkCharacterApiV1CharactersCharacterIdBookmarkPostRequestConfig(characterId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/characters/{character_id}/bookmark".replace("{"+"character_id"+"}", encodeURIComponent(characterId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Create Character
     * 
     * @param character 
     * @return ModelApiResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createCharacterApiV1CharactersPost(character: Character) : ModelApiResponse {
        val localVarResponse = createCharacterApiV1CharactersPostWithHttpInfo(character = character)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ModelApiResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Create Character
     * 
     * @param character 
     * @return ApiResponse<ModelApiResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun createCharacterApiV1CharactersPostWithHttpInfo(character: Character) : ApiResponse<ModelApiResponse?> {
        val localVariableConfig = createCharacterApiV1CharactersPostRequestConfig(character = character)

        return request<Character, ModelApiResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createCharacterApiV1CharactersPost
     *
     * @param character 
     * @return RequestConfig
     */
    fun createCharacterApiV1CharactersPostRequestConfig(character: Character) : RequestConfig<Character> {
        val localVariableBody = character
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/characters/",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Delete Character
     * 
     * @param characterId 
     * @return ModelApiResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun deleteCharacterApiV1CharactersCharacterIdDelete(characterId: java.util.UUID) : ModelApiResponse {
        val localVarResponse = deleteCharacterApiV1CharactersCharacterIdDeleteWithHttpInfo(characterId = characterId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ModelApiResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Delete Character
     * 
     * @param characterId 
     * @return ApiResponse<ModelApiResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun deleteCharacterApiV1CharactersCharacterIdDeleteWithHttpInfo(characterId: java.util.UUID) : ApiResponse<ModelApiResponse?> {
        val localVariableConfig = deleteCharacterApiV1CharactersCharacterIdDeleteRequestConfig(characterId = characterId)

        return request<Unit, ModelApiResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation deleteCharacterApiV1CharactersCharacterIdDelete
     *
     * @param characterId 
     * @return RequestConfig
     */
    fun deleteCharacterApiV1CharactersCharacterIdDeleteRequestConfig(characterId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/api/v1/characters/{character_id}".replace("{"+"character_id"+"}", encodeURIComponent(characterId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Get Character Bookmark State
     * 
     * @param characterId 
     * @return ApiResponseBookmarkState
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getCharacterBookmarkStateApiV1CharactersCharacterIdBookmarkGet(characterId: java.util.UUID) : ApiResponseBookmarkState {
        val localVarResponse = getCharacterBookmarkStateApiV1CharactersCharacterIdBookmarkGetWithHttpInfo(characterId = characterId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ApiResponseBookmarkState
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Get Character Bookmark State
     * 
     * @param characterId 
     * @return ApiResponse<ApiResponseBookmarkState?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getCharacterBookmarkStateApiV1CharactersCharacterIdBookmarkGetWithHttpInfo(characterId: java.util.UUID) : ApiResponse<ApiResponseBookmarkState?> {
        val localVariableConfig = getCharacterBookmarkStateApiV1CharactersCharacterIdBookmarkGetRequestConfig(characterId = characterId)

        return request<Unit, ApiResponseBookmarkState>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getCharacterBookmarkStateApiV1CharactersCharacterIdBookmarkGet
     *
     * @param characterId 
     * @return RequestConfig
     */
    fun getCharacterBookmarkStateApiV1CharactersCharacterIdBookmarkGetRequestConfig(characterId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/characters/{character_id}/bookmark".replace("{"+"character_id"+"}", encodeURIComponent(characterId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Get Character Details
     * 
     * @param characterId 
     * @return ApiResponseCharacter
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getCharacterDetailsApiV1CharactersCharacterIdGet(characterId: java.util.UUID) : ApiResponseCharacter {
        val localVarResponse = getCharacterDetailsApiV1CharactersCharacterIdGetWithHttpInfo(characterId = characterId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ApiResponseCharacter
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Get Character Details
     * 
     * @param characterId 
     * @return ApiResponse<ApiResponseCharacter?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getCharacterDetailsApiV1CharactersCharacterIdGetWithHttpInfo(characterId: java.util.UUID) : ApiResponse<ApiResponseCharacter?> {
        val localVariableConfig = getCharacterDetailsApiV1CharactersCharacterIdGetRequestConfig(characterId = characterId)

        return request<Unit, ApiResponseCharacter>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getCharacterDetailsApiV1CharactersCharacterIdGet
     *
     * @param characterId 
     * @return RequestConfig
     */
    fun getCharacterDetailsApiV1CharactersCharacterIdGetRequestConfig(characterId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/characters/{character_id}".replace("{"+"character_id"+"}", encodeURIComponent(characterId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Get Character Like State
     * 
     * @param characterId 
     * @return ApiResponseLikeState
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getCharacterLikeStateApiV1CharactersCharacterIdLikeGet(characterId: java.util.UUID) : ApiResponseLikeState {
        val localVarResponse = getCharacterLikeStateApiV1CharactersCharacterIdLikeGetWithHttpInfo(characterId = characterId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ApiResponseLikeState
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Get Character Like State
     * 
     * @param characterId 
     * @return ApiResponse<ApiResponseLikeState?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getCharacterLikeStateApiV1CharactersCharacterIdLikeGetWithHttpInfo(characterId: java.util.UUID) : ApiResponse<ApiResponseLikeState?> {
        val localVariableConfig = getCharacterLikeStateApiV1CharactersCharacterIdLikeGetRequestConfig(characterId = characterId)

        return request<Unit, ApiResponseLikeState>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getCharacterLikeStateApiV1CharactersCharacterIdLikeGet
     *
     * @param characterId 
     * @return RequestConfig
     */
    fun getCharacterLikeStateApiV1CharactersCharacterIdLikeGetRequestConfig(characterId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/characters/{character_id}/like".replace("{"+"character_id"+"}", encodeURIComponent(characterId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Like Character
     * 
     * @param characterId 
     * @return ApiResponseLikeState
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun likeCharacterApiV1CharactersCharacterIdLikePost(characterId: java.util.UUID) : ApiResponseLikeState {
        val localVarResponse = likeCharacterApiV1CharactersCharacterIdLikePostWithHttpInfo(characterId = characterId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ApiResponseLikeState
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Like Character
     * 
     * @param characterId 
     * @return ApiResponse<ApiResponseLikeState?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun likeCharacterApiV1CharactersCharacterIdLikePostWithHttpInfo(characterId: java.util.UUID) : ApiResponse<ApiResponseLikeState?> {
        val localVariableConfig = likeCharacterApiV1CharactersCharacterIdLikePostRequestConfig(characterId = characterId)

        return request<Unit, ApiResponseLikeState>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation likeCharacterApiV1CharactersCharacterIdLikePost
     *
     * @param characterId 
     * @return RequestConfig
     */
    fun likeCharacterApiV1CharactersCharacterIdLikePostRequestConfig(characterId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/characters/{character_id}/like".replace("{"+"character_id"+"}", encodeURIComponent(characterId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Search Character
     * 
     * @param ids  (optional)
     * @param ownerIds  (optional)
     * @param names  (optional)
     * @param bookmarkedBy  (optional)
     * @param limit  (optional, default to 50)
     * @param offset  (optional, default to 0)
     * @return ApiResponsePageCharacter
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun searchCharacterApiV1CharactersGet(ids: kotlin.collections.List<java.util.UUID>? = null, ownerIds: kotlin.collections.List<java.util.UUID>? = null, names: kotlin.collections.List<kotlin.String>? = null, bookmarkedBy: kotlin.collections.List<java.util.UUID>? = null, limit: kotlin.Int? = 50, offset: kotlin.Int? = 0) : ApiResponsePageCharacter {
        val localVarResponse = searchCharacterApiV1CharactersGetWithHttpInfo(ids = ids, ownerIds = ownerIds, names = names, bookmarkedBy = bookmarkedBy, limit = limit, offset = offset)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ApiResponsePageCharacter
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Search Character
     * 
     * @param ids  (optional)
     * @param ownerIds  (optional)
     * @param names  (optional)
     * @param bookmarkedBy  (optional)
     * @param limit  (optional, default to 50)
     * @param offset  (optional, default to 0)
     * @return ApiResponse<ApiResponsePageCharacter?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun searchCharacterApiV1CharactersGetWithHttpInfo(ids: kotlin.collections.List<java.util.UUID>?, ownerIds: kotlin.collections.List<java.util.UUID>?, names: kotlin.collections.List<kotlin.String>?, bookmarkedBy: kotlin.collections.List<java.util.UUID>?, limit: kotlin.Int?, offset: kotlin.Int?) : ApiResponse<ApiResponsePageCharacter?> {
        val localVariableConfig = searchCharacterApiV1CharactersGetRequestConfig(ids = ids, ownerIds = ownerIds, names = names, bookmarkedBy = bookmarkedBy, limit = limit, offset = offset)

        return request<Unit, ApiResponsePageCharacter>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation searchCharacterApiV1CharactersGet
     *
     * @param ids  (optional)
     * @param ownerIds  (optional)
     * @param names  (optional)
     * @param bookmarkedBy  (optional)
     * @param limit  (optional, default to 50)
     * @param offset  (optional, default to 0)
     * @return RequestConfig
     */
    fun searchCharacterApiV1CharactersGetRequestConfig(ids: kotlin.collections.List<java.util.UUID>?, ownerIds: kotlin.collections.List<java.util.UUID>?, names: kotlin.collections.List<kotlin.String>?, bookmarkedBy: kotlin.collections.List<java.util.UUID>?, limit: kotlin.Int?, offset: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (ids != null) {
                    put("ids", toMultiValue(ids.toList(), "multi"))
                }
                if (ownerIds != null) {
                    put("owner_ids", toMultiValue(ownerIds.toList(), "multi"))
                }
                if (names != null) {
                    put("names", toMultiValue(names.toList(), "multi"))
                }
                if (bookmarkedBy != null) {
                    put("bookmarked_by", toMultiValue(bookmarkedBy.toList(), "multi"))
                }
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (offset != null) {
                    put("offset", listOf(offset.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/characters/",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Unbookmark Character
     * 
     * @param characterId 
     * @return ApiResponseBookmarkState
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun unbookmarkCharacterApiV1CharactersCharacterIdBookmarkDelete(characterId: java.util.UUID) : ApiResponseBookmarkState {
        val localVarResponse = unbookmarkCharacterApiV1CharactersCharacterIdBookmarkDeleteWithHttpInfo(characterId = characterId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ApiResponseBookmarkState
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Unbookmark Character
     * 
     * @param characterId 
     * @return ApiResponse<ApiResponseBookmarkState?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun unbookmarkCharacterApiV1CharactersCharacterIdBookmarkDeleteWithHttpInfo(characterId: java.util.UUID) : ApiResponse<ApiResponseBookmarkState?> {
        val localVariableConfig = unbookmarkCharacterApiV1CharactersCharacterIdBookmarkDeleteRequestConfig(characterId = characterId)

        return request<Unit, ApiResponseBookmarkState>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation unbookmarkCharacterApiV1CharactersCharacterIdBookmarkDelete
     *
     * @param characterId 
     * @return RequestConfig
     */
    fun unbookmarkCharacterApiV1CharactersCharacterIdBookmarkDeleteRequestConfig(characterId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/api/v1/characters/{character_id}/bookmark".replace("{"+"character_id"+"}", encodeURIComponent(characterId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Unlike Character
     * 
     * @param characterId 
     * @return ApiResponseLikeState
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun unlikeCharacterApiV1CharactersCharacterIdLikeDelete(characterId: java.util.UUID) : ApiResponseLikeState {
        val localVarResponse = unlikeCharacterApiV1CharactersCharacterIdLikeDeleteWithHttpInfo(characterId = characterId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ApiResponseLikeState
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Unlike Character
     * 
     * @param characterId 
     * @return ApiResponse<ApiResponseLikeState?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun unlikeCharacterApiV1CharactersCharacterIdLikeDeleteWithHttpInfo(characterId: java.util.UUID) : ApiResponse<ApiResponseLikeState?> {
        val localVariableConfig = unlikeCharacterApiV1CharactersCharacterIdLikeDeleteRequestConfig(characterId = characterId)

        return request<Unit, ApiResponseLikeState>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation unlikeCharacterApiV1CharactersCharacterIdLikeDelete
     *
     * @param characterId 
     * @return RequestConfig
     */
    fun unlikeCharacterApiV1CharactersCharacterIdLikeDeleteRequestConfig(characterId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/api/v1/characters/{character_id}/like".replace("{"+"character_id"+"}", encodeURIComponent(characterId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Update Character
     * 
     * @param characterId 
     * @param character 
     * @return ModelApiResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun updateCharacterApiV1CharactersUpdateCharacterIdPost(characterId: java.util.UUID, character: Character) : ModelApiResponse {
        val localVarResponse = updateCharacterApiV1CharactersUpdateCharacterIdPostWithHttpInfo(characterId = characterId, character = character)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ModelApiResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Update Character
     * 
     * @param characterId 
     * @param character 
     * @return ApiResponse<ModelApiResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun updateCharacterApiV1CharactersUpdateCharacterIdPostWithHttpInfo(characterId: java.util.UUID, character: Character) : ApiResponse<ModelApiResponse?> {
        val localVariableConfig = updateCharacterApiV1CharactersUpdateCharacterIdPostRequestConfig(characterId = characterId, character = character)

        return request<Character, ModelApiResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation updateCharacterApiV1CharactersUpdateCharacterIdPost
     *
     * @param characterId 
     * @param character 
     * @return RequestConfig
     */
    fun updateCharacterApiV1CharactersUpdateCharacterIdPostRequestConfig(characterId: java.util.UUID, character: Character) : RequestConfig<Character> {
        val localVariableBody = character
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/characters/update/{character_id}".replace("{"+"character_id"+"}", encodeURIComponent(characterId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
