/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import java.io.IOException
import okhttp3.OkHttpClient
import okhttp3.HttpUrl

import org.openapitools.client.models.ApiResponseChatSettings
import org.openapitools.client.models.ChatSettings
import org.openapitools.client.models.HTTPValidationError

import com.squareup.moshi.Json

import org.openapitools.client.infrastructure.ApiClient
import org.openapitools.client.infrastructure.ApiResponse
import org.openapitools.client.infrastructure.ClientException
import org.openapitools.client.infrastructure.ClientError
import org.openapitools.client.infrastructure.ServerException
import org.openapitools.client.infrastructure.ServerError
import org.openapitools.client.infrastructure.MultiValueMap
import org.openapitools.client.infrastructure.PartConfig
import org.openapitools.client.infrastructure.RequestConfig
import org.openapitools.client.infrastructure.RequestMethod
import org.openapitools.client.infrastructure.ResponseType
import org.openapitools.client.infrastructure.Success
import org.openapitools.client.infrastructure.toMultiValue

class ChatSettingsApi(basePath: kotlin.String = defaultBasePath, client: OkHttpClient = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost")
        }
    }

    /**
     * Get Chat Settings
     * 
     * @param chatId 
     * @return ApiResponseChatSettings
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getChatSettingsApiV1ChatsChatIdSettingsGet(chatId: java.util.UUID) : ApiResponseChatSettings {
        val localVarResponse = getChatSettingsApiV1ChatsChatIdSettingsGetWithHttpInfo(chatId = chatId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ApiResponseChatSettings
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Get Chat Settings
     * 
     * @param chatId 
     * @return ApiResponse<ApiResponseChatSettings?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getChatSettingsApiV1ChatsChatIdSettingsGetWithHttpInfo(chatId: java.util.UUID) : ApiResponse<ApiResponseChatSettings?> {
        val localVariableConfig = getChatSettingsApiV1ChatsChatIdSettingsGetRequestConfig(chatId = chatId)

        return request<Unit, ApiResponseChatSettings>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getChatSettingsApiV1ChatsChatIdSettingsGet
     *
     * @param chatId 
     * @return RequestConfig
     */
    fun getChatSettingsApiV1ChatsChatIdSettingsGetRequestConfig(chatId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/chats/{chat_id}/settings".replace("{"+"chat_id"+"}", encodeURIComponent(chatId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Upsert Chat Settings
     * 
     * @param chatId 
     * @param chatSettings 
     * @return ApiResponseChatSettings
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun upsertChatSettingsApiV1ChatsChatIdSettingsPut(chatId: java.util.UUID, chatSettings: ChatSettings) : ApiResponseChatSettings {
        val localVarResponse = upsertChatSettingsApiV1ChatsChatIdSettingsPutWithHttpInfo(chatId = chatId, chatSettings = chatSettings)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ApiResponseChatSettings
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Upsert Chat Settings
     * 
     * @param chatId 
     * @param chatSettings 
     * @return ApiResponse<ApiResponseChatSettings?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun upsertChatSettingsApiV1ChatsChatIdSettingsPutWithHttpInfo(chatId: java.util.UUID, chatSettings: ChatSettings) : ApiResponse<ApiResponseChatSettings?> {
        val localVariableConfig = upsertChatSettingsApiV1ChatsChatIdSettingsPutRequestConfig(chatId = chatId, chatSettings = chatSettings)

        return request<ChatSettings, ApiResponseChatSettings>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation upsertChatSettingsApiV1ChatsChatIdSettingsPut
     *
     * @param chatId 
     * @param chatSettings 
     * @return RequestConfig
     */
    fun upsertChatSettingsApiV1ChatsChatIdSettingsPutRequestConfig(chatId: java.util.UUID, chatSettings: ChatSettings) : RequestConfig<ChatSettings> {
        val localVariableBody = chatSettings
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/api/v1/chats/{chat_id}/settings".replace("{"+"chat_id"+"}", encodeURIComponent(chatId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
