/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import java.io.IOException
import okhttp3.OkHttpClient
import okhttp3.HttpUrl

import org.openapitools.client.models.ApiResponseChat
import org.openapitools.client.models.ApiResponseContextUsage
import org.openapitools.client.models.ApiResponsePageChat
import org.openapitools.client.models.BodyChooseChatInitialMessageApiV1ChatsChatIdInitialMessagePost
import org.openapitools.client.models.BodySetChatPersonaApiV1ChatsChatIdPersonaPost
import org.openapitools.client.models.BodyUpdateChatApiV1ChatsUpdateChatIdPost
import org.openapitools.client.models.CreateChatRequest
import org.openapitools.client.models.HTTPValidationError
import org.openapitools.client.models.ModelApiResponse

import com.squareup.moshi.Json

import org.openapitools.client.infrastructure.ApiClient
import org.openapitools.client.infrastructure.ApiResponse
import org.openapitools.client.infrastructure.ClientException
import org.openapitools.client.infrastructure.ClientError
import org.openapitools.client.infrastructure.ServerException
import org.openapitools.client.infrastructure.ServerError
import org.openapitools.client.infrastructure.MultiValueMap
import org.openapitools.client.infrastructure.PartConfig
import org.openapitools.client.infrastructure.RequestConfig
import org.openapitools.client.infrastructure.RequestMethod
import org.openapitools.client.infrastructure.ResponseType
import org.openapitools.client.infrastructure.Success
import org.openapitools.client.infrastructure.toMultiValue

class ChatsApi(basePath: kotlin.String = defaultBasePath, client: OkHttpClient = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost")
        }
    }

    /**
     * Choose Chat Initial Message
     * 
     * @param chatId 
     * @param bodyChooseChatInitialMessageApiV1ChatsChatIdInitialMessagePost 
     * @return ModelApiResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun chooseChatInitialMessageApiV1ChatsChatIdInitialMessagePost(chatId: java.util.UUID, bodyChooseChatInitialMessageApiV1ChatsChatIdInitialMessagePost: BodyChooseChatInitialMessageApiV1ChatsChatIdInitialMessagePost) : ModelApiResponse {
        val localVarResponse = chooseChatInitialMessageApiV1ChatsChatIdInitialMessagePostWithHttpInfo(chatId = chatId, bodyChooseChatInitialMessageApiV1ChatsChatIdInitialMessagePost = bodyChooseChatInitialMessageApiV1ChatsChatIdInitialMessagePost)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ModelApiResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Choose Chat Initial Message
     * 
     * @param chatId 
     * @param bodyChooseChatInitialMessageApiV1ChatsChatIdInitialMessagePost 
     * @return ApiResponse<ModelApiResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun chooseChatInitialMessageApiV1ChatsChatIdInitialMessagePostWithHttpInfo(chatId: java.util.UUID, bodyChooseChatInitialMessageApiV1ChatsChatIdInitialMessagePost: BodyChooseChatInitialMessageApiV1ChatsChatIdInitialMessagePost) : ApiResponse<ModelApiResponse?> {
        val localVariableConfig = chooseChatInitialMessageApiV1ChatsChatIdInitialMessagePostRequestConfig(chatId = chatId, bodyChooseChatInitialMessageApiV1ChatsChatIdInitialMessagePost = bodyChooseChatInitialMessageApiV1ChatsChatIdInitialMessagePost)

        return request<BodyChooseChatInitialMessageApiV1ChatsChatIdInitialMessagePost, ModelApiResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation chooseChatInitialMessageApiV1ChatsChatIdInitialMessagePost
     *
     * @param chatId 
     * @param bodyChooseChatInitialMessageApiV1ChatsChatIdInitialMessagePost 
     * @return RequestConfig
     */
    fun chooseChatInitialMessageApiV1ChatsChatIdInitialMessagePostRequestConfig(chatId: java.util.UUID, bodyChooseChatInitialMessageApiV1ChatsChatIdInitialMessagePost: BodyChooseChatInitialMessageApiV1ChatsChatIdInitialMessagePost) : RequestConfig<BodyChooseChatInitialMessageApiV1ChatsChatIdInitialMessagePost> {
        val localVariableBody = bodyChooseChatInitialMessageApiV1ChatsChatIdInitialMessagePost
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/chats/{chat_id}/initial-message".replace("{"+"chat_id"+"}", encodeURIComponent(chatId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Create Chat
     * 
     * @param createChatRequest 
     * @return ModelApiResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createChatApiV1ChatsPost(createChatRequest: CreateChatRequest) : ModelApiResponse {
        val localVarResponse = createChatApiV1ChatsPostWithHttpInfo(createChatRequest = createChatRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ModelApiResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Create Chat
     * 
     * @param createChatRequest 
     * @return ApiResponse<ModelApiResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun createChatApiV1ChatsPostWithHttpInfo(createChatRequest: CreateChatRequest) : ApiResponse<ModelApiResponse?> {
        val localVariableConfig = createChatApiV1ChatsPostRequestConfig(createChatRequest = createChatRequest)

        return request<CreateChatRequest, ModelApiResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createChatApiV1ChatsPost
     *
     * @param createChatRequest 
     * @return RequestConfig
     */
    fun createChatApiV1ChatsPostRequestConfig(createChatRequest: CreateChatRequest) : RequestConfig<CreateChatRequest> {
        val localVariableBody = createChatRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/chats/",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Delete Chat
     * 
     * @param chatId 
     * @return ModelApiResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun deleteChatApiV1ChatsChatIdDelete(chatId: java.util.UUID) : ModelApiResponse {
        val localVarResponse = deleteChatApiV1ChatsChatIdDeleteWithHttpInfo(chatId = chatId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ModelApiResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Delete Chat
     * 
     * @param chatId 
     * @return ApiResponse<ModelApiResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun deleteChatApiV1ChatsChatIdDeleteWithHttpInfo(chatId: java.util.UUID) : ApiResponse<ModelApiResponse?> {
        val localVariableConfig = deleteChatApiV1ChatsChatIdDeleteRequestConfig(chatId = chatId)

        return request<Unit, ModelApiResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation deleteChatApiV1ChatsChatIdDelete
     *
     * @param chatId 
     * @return RequestConfig
     */
    fun deleteChatApiV1ChatsChatIdDeleteRequestConfig(chatId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/api/v1/chats/{chat_id}".replace("{"+"chat_id"+"}", encodeURIComponent(chatId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Get Chat Context Usage
     * 
     * @param chatId 
     * @return ApiResponseContextUsage
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getChatContextUsageApiV1ChatsChatIdContextUsageGet(chatId: java.util.UUID) : ApiResponseContextUsage {
        val localVarResponse = getChatContextUsageApiV1ChatsChatIdContextUsageGetWithHttpInfo(chatId = chatId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ApiResponseContextUsage
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Get Chat Context Usage
     * 
     * @param chatId 
     * @return ApiResponse<ApiResponseContextUsage?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getChatContextUsageApiV1ChatsChatIdContextUsageGetWithHttpInfo(chatId: java.util.UUID) : ApiResponse<ApiResponseContextUsage?> {
        val localVariableConfig = getChatContextUsageApiV1ChatsChatIdContextUsageGetRequestConfig(chatId = chatId)

        return request<Unit, ApiResponseContextUsage>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getChatContextUsageApiV1ChatsChatIdContextUsageGet
     *
     * @param chatId 
     * @return RequestConfig
     */
    fun getChatContextUsageApiV1ChatsChatIdContextUsageGetRequestConfig(chatId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/chats/{chat_id}/context-usage".replace("{"+"chat_id"+"}", encodeURIComponent(chatId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Get Chat Details
     * 
     * @param chatId 
     * @return ApiResponseChat
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getChatDetailsApiV1ChatsChatIdGet(chatId: java.util.UUID) : ApiResponseChat {
        val localVarResponse = getChatDetailsApiV1ChatsChatIdGetWithHttpInfo(chatId = chatId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ApiResponseChat
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Get Chat Details
     * 
     * @param chatId 
     * @return ApiResponse<ApiResponseChat?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getChatDetailsApiV1ChatsChatIdGetWithHttpInfo(chatId: java.util.UUID) : ApiResponse<ApiResponseChat?> {
        val localVariableConfig = getChatDetailsApiV1ChatsChatIdGetRequestConfig(chatId = chatId)

        return request<Unit, ApiResponseChat>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getChatDetailsApiV1ChatsChatIdGet
     *
     * @param chatId 
     * @return RequestConfig
     */
    fun getChatDetailsApiV1ChatsChatIdGetRequestConfig(chatId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/chats/{chat_id}".replace("{"+"chat_id"+"}", encodeURIComponent(chatId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Search Chats
     * 
     * @param ids  (optional)
     * @param titles  (optional)
     * @param userIds  (optional)
     * @param sceneIds  (optional)
     * @param limit  (optional, default to 50)
     * @param offset  (optional, default to 0)
     * @return ApiResponsePageChat
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun searchChatsApiV1ChatsGet(ids: kotlin.collections.List<java.util.UUID>? = null, titles: kotlin.collections.List<kotlin.String>? = null, userIds: kotlin.collections.List<java.util.UUID>? = null, sceneIds: kotlin.collections.List<java.util.UUID>? = null, limit: kotlin.Int? = 50, offset: kotlin.Int? = 0) : ApiResponsePageChat {
        val localVarResponse = searchChatsApiV1ChatsGetWithHttpInfo(ids = ids, titles = titles, userIds = userIds, sceneIds = sceneIds, limit = limit, offset = offset)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ApiResponsePageChat
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Search Chats
     * 
     * @param ids  (optional)
     * @param titles  (optional)
     * @param userIds  (optional)
     * @param sceneIds  (optional)
     * @param limit  (optional, default to 50)
     * @param offset  (optional, default to 0)
     * @return ApiResponse<ApiResponsePageChat?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun searchChatsApiV1ChatsGetWithHttpInfo(ids: kotlin.collections.List<java.util.UUID>?, titles: kotlin.collections.List<kotlin.String>?, userIds: kotlin.collections.List<java.util.UUID>?, sceneIds: kotlin.collections.List<java.util.UUID>?, limit: kotlin.Int?, offset: kotlin.Int?) : ApiResponse<ApiResponsePageChat?> {
        val localVariableConfig = searchChatsApiV1ChatsGetRequestConfig(ids = ids, titles = titles, userIds = userIds, sceneIds = sceneIds, limit = limit, offset = offset)

        return request<Unit, ApiResponsePageChat>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation searchChatsApiV1ChatsGet
     *
     * @param ids  (optional)
     * @param titles  (optional)
     * @param userIds  (optional)
     * @param sceneIds  (optional)
     * @param limit  (optional, default to 50)
     * @param offset  (optional, default to 0)
     * @return RequestConfig
     */
    fun searchChatsApiV1ChatsGetRequestConfig(ids: kotlin.collections.List<java.util.UUID>?, titles: kotlin.collections.List<kotlin.String>?, userIds: kotlin.collections.List<java.util.UUID>?, sceneIds: kotlin.collections.List<java.util.UUID>?, limit: kotlin.Int?, offset: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (ids != null) {
                    put("ids", toMultiValue(ids.toList(), "multi"))
                }
                if (titles != null) {
                    put("titles", toMultiValue(titles.toList(), "multi"))
                }
                if (userIds != null) {
                    put("user_ids", toMultiValue(userIds.toList(), "multi"))
                }
                if (sceneIds != null) {
                    put("scene_ids", toMultiValue(sceneIds.toList(), "multi"))
                }
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (offset != null) {
                    put("offset", listOf(offset.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/chats/",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Set Chat Persona
     * 
     * @param chatId 
     * @param bodySetChatPersonaApiV1ChatsChatIdPersonaPost 
     * @return ModelApiResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun setChatPersonaApiV1ChatsChatIdPersonaPost(chatId: java.util.UUID, bodySetChatPersonaApiV1ChatsChatIdPersonaPost: BodySetChatPersonaApiV1ChatsChatIdPersonaPost) : ModelApiResponse {
        val localVarResponse = setChatPersonaApiV1ChatsChatIdPersonaPostWithHttpInfo(chatId = chatId, bodySetChatPersonaApiV1ChatsChatIdPersonaPost = bodySetChatPersonaApiV1ChatsChatIdPersonaPost)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ModelApiResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Set Chat Persona
     * 
     * @param chatId 
     * @param bodySetChatPersonaApiV1ChatsChatIdPersonaPost 
     * @return ApiResponse<ModelApiResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun setChatPersonaApiV1ChatsChatIdPersonaPostWithHttpInfo(chatId: java.util.UUID, bodySetChatPersonaApiV1ChatsChatIdPersonaPost: BodySetChatPersonaApiV1ChatsChatIdPersonaPost) : ApiResponse<ModelApiResponse?> {
        val localVariableConfig = setChatPersonaApiV1ChatsChatIdPersonaPostRequestConfig(chatId = chatId, bodySetChatPersonaApiV1ChatsChatIdPersonaPost = bodySetChatPersonaApiV1ChatsChatIdPersonaPost)

        return request<BodySetChatPersonaApiV1ChatsChatIdPersonaPost, ModelApiResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation setChatPersonaApiV1ChatsChatIdPersonaPost
     *
     * @param chatId 
     * @param bodySetChatPersonaApiV1ChatsChatIdPersonaPost 
     * @return RequestConfig
     */
    fun setChatPersonaApiV1ChatsChatIdPersonaPostRequestConfig(chatId: java.util.UUID, bodySetChatPersonaApiV1ChatsChatIdPersonaPost: BodySetChatPersonaApiV1ChatsChatIdPersonaPost) : RequestConfig<BodySetChatPersonaApiV1ChatsChatIdPersonaPost> {
        val localVariableBody = bodySetChatPersonaApiV1ChatsChatIdPersonaPost
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/chats/{chat_id}/persona".replace("{"+"chat_id"+"}", encodeURIComponent(chatId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Stream Chat Events
     * 
     * @param chatId 
     * @return kotlin.Any
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun streamChatEventsApiV1ChatsChatIdEventsGet(chatId: java.util.UUID) : kotlin.Any {
        val localVarResponse = streamChatEventsApiV1ChatsChatIdEventsGetWithHttpInfo(chatId = chatId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.Any
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Stream Chat Events
     * 
     * @param chatId 
     * @return ApiResponse<kotlin.Any?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun streamChatEventsApiV1ChatsChatIdEventsGetWithHttpInfo(chatId: java.util.UUID) : ApiResponse<kotlin.Any?> {
        val localVariableConfig = streamChatEventsApiV1ChatsChatIdEventsGetRequestConfig(chatId = chatId)

        return request<Unit, kotlin.Any>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation streamChatEventsApiV1ChatsChatIdEventsGet
     *
     * @param chatId 
     * @return RequestConfig
     */
    fun streamChatEventsApiV1ChatsChatIdEventsGetRequestConfig(chatId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/chats/{chat_id}/events".replace("{"+"chat_id"+"}", encodeURIComponent(chatId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Update Chat
     * 
     * @param chatId 
     * @param bodyUpdateChatApiV1ChatsUpdateChatIdPost 
     * @return ModelApiResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun updateChatApiV1ChatsUpdateChatIdPost(chatId: java.util.UUID, bodyUpdateChatApiV1ChatsUpdateChatIdPost: BodyUpdateChatApiV1ChatsUpdateChatIdPost) : ModelApiResponse {
        val localVarResponse = updateChatApiV1ChatsUpdateChatIdPostWithHttpInfo(chatId = chatId, bodyUpdateChatApiV1ChatsUpdateChatIdPost = bodyUpdateChatApiV1ChatsUpdateChatIdPost)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ModelApiResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Update Chat
     * 
     * @param chatId 
     * @param bodyUpdateChatApiV1ChatsUpdateChatIdPost 
     * @return ApiResponse<ModelApiResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun updateChatApiV1ChatsUpdateChatIdPostWithHttpInfo(chatId: java.util.UUID, bodyUpdateChatApiV1ChatsUpdateChatIdPost: BodyUpdateChatApiV1ChatsUpdateChatIdPost) : ApiResponse<ModelApiResponse?> {
        val localVariableConfig = updateChatApiV1ChatsUpdateChatIdPostRequestConfig(chatId = chatId, bodyUpdateChatApiV1ChatsUpdateChatIdPost = bodyUpdateChatApiV1ChatsUpdateChatIdPost)

        return request<BodyUpdateChatApiV1ChatsUpdateChatIdPost, ModelApiResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation updateChatApiV1ChatsUpdateChatIdPost
     *
     * @param chatId 
     * @param bodyUpdateChatApiV1ChatsUpdateChatIdPost 
     * @return RequestConfig
     */
    fun updateChatApiV1ChatsUpdateChatIdPostRequestConfig(chatId: java.util.UUID, bodyUpdateChatApiV1ChatsUpdateChatIdPost: BodyUpdateChatApiV1ChatsUpdateChatIdPost) : RequestConfig<BodyUpdateChatApiV1ChatsUpdateChatIdPost> {
        val localVariableBody = bodyUpdateChatApiV1ChatsUpdateChatIdPost
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/chats/update/{chat_id}".replace("{"+"chat_id"+"}", encodeURIComponent(chatId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
