/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import java.io.IOException
import okhttp3.OkHttpClient
import okhttp3.HttpUrl

import org.openapitools.client.models.ApiResponseChat
import org.openapitools.client.models.ApiResponsePageChat
import org.openapitools.client.models.BodyUpdateChatApiV1ChatsUpdateChatIdPost
import org.openapitools.client.models.Chat
import org.openapitools.client.models.HTTPValidationError
import org.openapitools.client.models.ModelApiResponse

import com.squareup.moshi.Json

import org.openapitools.client.infrastructure.ApiClient
import org.openapitools.client.infrastructure.ApiResponse
import org.openapitools.client.infrastructure.ClientException
import org.openapitools.client.infrastructure.ClientError
import org.openapitools.client.infrastructure.ServerException
import org.openapitools.client.infrastructure.ServerError
import org.openapitools.client.infrastructure.MultiValueMap
import org.openapitools.client.infrastructure.PartConfig
import org.openapitools.client.infrastructure.RequestConfig
import org.openapitools.client.infrastructure.RequestMethod
import org.openapitools.client.infrastructure.ResponseType
import org.openapitools.client.infrastructure.Success
import org.openapitools.client.infrastructure.toMultiValue

class ChatsApi(basePath: kotlin.String = defaultBasePath, client: OkHttpClient = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost")
        }
    }

    /**
     * Create Chat
     * 
     * @param chat 
     * @return ModelApiResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createChatApiV1ChatsPost(chat: Chat) : ModelApiResponse {
        val localVarResponse = createChatApiV1ChatsPostWithHttpInfo(chat = chat)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ModelApiResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Create Chat
     * 
     * @param chat 
     * @return ApiResponse<ModelApiResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun createChatApiV1ChatsPostWithHttpInfo(chat: Chat) : ApiResponse<ModelApiResponse?> {
        val localVariableConfig = createChatApiV1ChatsPostRequestConfig(chat = chat)

        return request<Chat, ModelApiResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createChatApiV1ChatsPost
     *
     * @param chat 
     * @return RequestConfig
     */
    fun createChatApiV1ChatsPostRequestConfig(chat: Chat) : RequestConfig<Chat> {
        val localVariableBody = chat
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/chats/",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Delete Chat
     * 
     * @param chatId 
     * @return ModelApiResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun deleteChatApiV1ChatsChatIdDelete(chatId: java.util.UUID) : ModelApiResponse {
        val localVarResponse = deleteChatApiV1ChatsChatIdDeleteWithHttpInfo(chatId = chatId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ModelApiResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Delete Chat
     * 
     * @param chatId 
     * @return ApiResponse<ModelApiResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun deleteChatApiV1ChatsChatIdDeleteWithHttpInfo(chatId: java.util.UUID) : ApiResponse<ModelApiResponse?> {
        val localVariableConfig = deleteChatApiV1ChatsChatIdDeleteRequestConfig(chatId = chatId)

        return request<Unit, ModelApiResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation deleteChatApiV1ChatsChatIdDelete
     *
     * @param chatId 
     * @return RequestConfig
     */
    fun deleteChatApiV1ChatsChatIdDeleteRequestConfig(chatId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/api/v1/chats/{chat_id}".replace("{"+"chat_id"+"}", encodeURIComponent(chatId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Get Chat Details
     * 
     * @param chatId 
     * @return ApiResponseChat
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getChatDetailsApiV1ChatsChatIdGet(chatId: java.util.UUID) : ApiResponseChat {
        val localVarResponse = getChatDetailsApiV1ChatsChatIdGetWithHttpInfo(chatId = chatId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ApiResponseChat
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Get Chat Details
     * 
     * @param chatId 
     * @return ApiResponse<ApiResponseChat?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getChatDetailsApiV1ChatsChatIdGetWithHttpInfo(chatId: java.util.UUID) : ApiResponse<ApiResponseChat?> {
        val localVariableConfig = getChatDetailsApiV1ChatsChatIdGetRequestConfig(chatId = chatId)

        return request<Unit, ApiResponseChat>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getChatDetailsApiV1ChatsChatIdGet
     *
     * @param chatId 
     * @return RequestConfig
     */
    fun getChatDetailsApiV1ChatsChatIdGetRequestConfig(chatId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/chats/{chat_id}".replace("{"+"chat_id"+"}", encodeURIComponent(chatId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Search Chats
     * 
     * @param ids  (optional)
     * @param titles  (optional)
     * @param userIds  (optional)
     * @param sceneIds  (optional)
     * @param limit  (optional, default to 50)
     * @param offset  (optional, default to 0)
     * @return ApiResponsePageChat
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun searchChatsApiV1ChatsGet(ids: kotlin.collections.List<java.util.UUID>? = null, titles: kotlin.collections.List<kotlin.String>? = null, userIds: kotlin.collections.List<java.util.UUID>? = null, sceneIds: kotlin.collections.List<java.util.UUID>? = null, limit: kotlin.Int? = 50, offset: kotlin.Int? = 0) : ApiResponsePageChat {
        val localVarResponse = searchChatsApiV1ChatsGetWithHttpInfo(ids = ids, titles = titles, userIds = userIds, sceneIds = sceneIds, limit = limit, offset = offset)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ApiResponsePageChat
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Search Chats
     * 
     * @param ids  (optional)
     * @param titles  (optional)
     * @param userIds  (optional)
     * @param sceneIds  (optional)
     * @param limit  (optional, default to 50)
     * @param offset  (optional, default to 0)
     * @return ApiResponse<ApiResponsePageChat?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun searchChatsApiV1ChatsGetWithHttpInfo(ids: kotlin.collections.List<java.util.UUID>?, titles: kotlin.collections.List<kotlin.String>?, userIds: kotlin.collections.List<java.util.UUID>?, sceneIds: kotlin.collections.List<java.util.UUID>?, limit: kotlin.Int?, offset: kotlin.Int?) : ApiResponse<ApiResponsePageChat?> {
        val localVariableConfig = searchChatsApiV1ChatsGetRequestConfig(ids = ids, titles = titles, userIds = userIds, sceneIds = sceneIds, limit = limit, offset = offset)

        return request<Unit, ApiResponsePageChat>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation searchChatsApiV1ChatsGet
     *
     * @param ids  (optional)
     * @param titles  (optional)
     * @param userIds  (optional)
     * @param sceneIds  (optional)
     * @param limit  (optional, default to 50)
     * @param offset  (optional, default to 0)
     * @return RequestConfig
     */
    fun searchChatsApiV1ChatsGetRequestConfig(ids: kotlin.collections.List<java.util.UUID>?, titles: kotlin.collections.List<kotlin.String>?, userIds: kotlin.collections.List<java.util.UUID>?, sceneIds: kotlin.collections.List<java.util.UUID>?, limit: kotlin.Int?, offset: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (ids != null) {
                    put("ids", toMultiValue(ids.toList(), "multi"))
                }
                if (titles != null) {
                    put("titles", toMultiValue(titles.toList(), "multi"))
                }
                if (userIds != null) {
                    put("user_ids", toMultiValue(userIds.toList(), "multi"))
                }
                if (sceneIds != null) {
                    put("scene_ids", toMultiValue(sceneIds.toList(), "multi"))
                }
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (offset != null) {
                    put("offset", listOf(offset.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/chats/",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Update Chat
     * 
     * @param chatId 
     * @param bodyUpdateChatApiV1ChatsUpdateChatIdPost 
     * @return ModelApiResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun updateChatApiV1ChatsUpdateChatIdPost(chatId: java.util.UUID, bodyUpdateChatApiV1ChatsUpdateChatIdPost: BodyUpdateChatApiV1ChatsUpdateChatIdPost) : ModelApiResponse {
        val localVarResponse = updateChatApiV1ChatsUpdateChatIdPostWithHttpInfo(chatId = chatId, bodyUpdateChatApiV1ChatsUpdateChatIdPost = bodyUpdateChatApiV1ChatsUpdateChatIdPost)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ModelApiResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Update Chat
     * 
     * @param chatId 
     * @param bodyUpdateChatApiV1ChatsUpdateChatIdPost 
     * @return ApiResponse<ModelApiResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun updateChatApiV1ChatsUpdateChatIdPostWithHttpInfo(chatId: java.util.UUID, bodyUpdateChatApiV1ChatsUpdateChatIdPost: BodyUpdateChatApiV1ChatsUpdateChatIdPost) : ApiResponse<ModelApiResponse?> {
        val localVariableConfig = updateChatApiV1ChatsUpdateChatIdPostRequestConfig(chatId = chatId, bodyUpdateChatApiV1ChatsUpdateChatIdPost = bodyUpdateChatApiV1ChatsUpdateChatIdPost)

        return request<BodyUpdateChatApiV1ChatsUpdateChatIdPost, ModelApiResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation updateChatApiV1ChatsUpdateChatIdPost
     *
     * @param chatId 
     * @param bodyUpdateChatApiV1ChatsUpdateChatIdPost 
     * @return RequestConfig
     */
    fun updateChatApiV1ChatsUpdateChatIdPostRequestConfig(chatId: java.util.UUID, bodyUpdateChatApiV1ChatsUpdateChatIdPost: BodyUpdateChatApiV1ChatsUpdateChatIdPost) : RequestConfig<BodyUpdateChatApiV1ChatsUpdateChatIdPost> {
        val localVariableBody = bodyUpdateChatApiV1ChatsUpdateChatIdPost
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/chats/update/{chat_id}".replace("{"+"chat_id"+"}", encodeURIComponent(chatId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
