/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import java.io.IOException
import okhttp3.OkHttpClient
import okhttp3.HttpUrl

import org.openapitools.client.models.ApiResponseImportLorebookResultDTO
import org.openapitools.client.models.ApiResponseImportPreviewDTO
import org.openapitools.client.models.HTTPValidationError

import com.squareup.moshi.Json

import org.openapitools.client.infrastructure.ApiClient
import org.openapitools.client.infrastructure.ApiResponse
import org.openapitools.client.infrastructure.ClientException
import org.openapitools.client.infrastructure.ClientError
import org.openapitools.client.infrastructure.ServerException
import org.openapitools.client.infrastructure.ServerError
import org.openapitools.client.infrastructure.MultiValueMap
import org.openapitools.client.infrastructure.PartConfig
import org.openapitools.client.infrastructure.RequestConfig
import org.openapitools.client.infrastructure.RequestMethod
import org.openapitools.client.infrastructure.ResponseType
import org.openapitools.client.infrastructure.Success
import org.openapitools.client.infrastructure.toMultiValue

class ImportApi(basePath: kotlin.String = defaultBasePath, client: OkHttpClient = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost")
        }
    }

    /**
     * Import Lorebook
     * 
     * @param file SillyTavern World Info / lorebook JSON
     * @param isPublic  (optional, default to false)
     * @param importImages  (optional, default to true)
     * @param selectedKeys Entry keys to import; omit to import all (optional)
     * @param linkScenes Link every created character to each created scene (optional, default to true)
     * @return ApiResponseImportLorebookResultDTO
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun importLorebookApiV1ImportLorebookPost(file: kotlin.String, isPublic: kotlin.Boolean? = false, importImages: kotlin.Boolean? = true, selectedKeys: kotlin.collections.List<kotlin.String>? = null, linkScenes: kotlin.Boolean? = true) : ApiResponseImportLorebookResultDTO {
        val localVarResponse = importLorebookApiV1ImportLorebookPostWithHttpInfo(file = file, isPublic = isPublic, importImages = importImages, selectedKeys = selectedKeys, linkScenes = linkScenes)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ApiResponseImportLorebookResultDTO
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Import Lorebook
     * 
     * @param file SillyTavern World Info / lorebook JSON
     * @param isPublic  (optional, default to false)
     * @param importImages  (optional, default to true)
     * @param selectedKeys Entry keys to import; omit to import all (optional)
     * @param linkScenes Link every created character to each created scene (optional, default to true)
     * @return ApiResponse<ApiResponseImportLorebookResultDTO?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun importLorebookApiV1ImportLorebookPostWithHttpInfo(file: kotlin.String, isPublic: kotlin.Boolean?, importImages: kotlin.Boolean?, selectedKeys: kotlin.collections.List<kotlin.String>?, linkScenes: kotlin.Boolean?) : ApiResponse<ApiResponseImportLorebookResultDTO?> {
        val localVariableConfig = importLorebookApiV1ImportLorebookPostRequestConfig(file = file, isPublic = isPublic, importImages = importImages, selectedKeys = selectedKeys, linkScenes = linkScenes)

        return request<Map<String, PartConfig<*>>, ApiResponseImportLorebookResultDTO>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation importLorebookApiV1ImportLorebookPost
     *
     * @param file SillyTavern World Info / lorebook JSON
     * @param isPublic  (optional, default to false)
     * @param importImages  (optional, default to true)
     * @param selectedKeys Entry keys to import; omit to import all (optional)
     * @param linkScenes Link every created character to each created scene (optional, default to true)
     * @return RequestConfig
     */
    fun importLorebookApiV1ImportLorebookPostRequestConfig(file: kotlin.String, isPublic: kotlin.Boolean?, importImages: kotlin.Boolean?, selectedKeys: kotlin.collections.List<kotlin.String>?, linkScenes: kotlin.Boolean?) : RequestConfig<Map<String, PartConfig<*>>> {
        val localVariableBody = mapOf(
            "file" to PartConfig(body = file, headers = mutableMapOf()),
            "is_public" to PartConfig(body = isPublic, headers = mutableMapOf()),
            "import_images" to PartConfig(body = importImages, headers = mutableMapOf()),
            "selected_keys" to PartConfig(body = selectedKeys, headers = mutableMapOf()),
            "link_scenes" to PartConfig(body = linkScenes, headers = mutableMapOf()),)
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf("Content-Type" to "multipart/form-data")
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/import/lorebook",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Preview Lorebook
     * Parse-only preview: returns the candidate characters &amp; scenes found in the file so the client can let the user pick. No DB writes.
     * @param file SillyTavern World Info / lorebook JSON
     * @return ApiResponseImportPreviewDTO
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun previewLorebookApiV1ImportLorebookPreviewPost(file: kotlin.String) : ApiResponseImportPreviewDTO {
        val localVarResponse = previewLorebookApiV1ImportLorebookPreviewPostWithHttpInfo(file = file)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ApiResponseImportPreviewDTO
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Preview Lorebook
     * Parse-only preview: returns the candidate characters &amp; scenes found in the file so the client can let the user pick. No DB writes.
     * @param file SillyTavern World Info / lorebook JSON
     * @return ApiResponse<ApiResponseImportPreviewDTO?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun previewLorebookApiV1ImportLorebookPreviewPostWithHttpInfo(file: kotlin.String) : ApiResponse<ApiResponseImportPreviewDTO?> {
        val localVariableConfig = previewLorebookApiV1ImportLorebookPreviewPostRequestConfig(file = file)

        return request<Map<String, PartConfig<*>>, ApiResponseImportPreviewDTO>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation previewLorebookApiV1ImportLorebookPreviewPost
     *
     * @param file SillyTavern World Info / lorebook JSON
     * @return RequestConfig
     */
    fun previewLorebookApiV1ImportLorebookPreviewPostRequestConfig(file: kotlin.String) : RequestConfig<Map<String, PartConfig<*>>> {
        val localVariableBody = mapOf(
            "file" to PartConfig(body = file, headers = mutableMapOf()),)
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf("Content-Type" to "multipart/form-data")
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/import/lorebook/preview",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
