/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import java.io.IOException
import okhttp3.OkHttpClient
import okhttp3.HttpUrl

import org.openapitools.client.models.ApiResponseListMediaAssetDTO
import org.openapitools.client.models.ApiResponseMediaAssetDTO
import org.openapitools.client.models.ApiResponsePageMediaAssetDTO
import org.openapitools.client.models.HTTPValidationError
import org.openapitools.client.models.MediaEntityType
import org.openapitools.client.models.ModelApiResponse

import com.squareup.moshi.Json

import org.openapitools.client.infrastructure.ApiClient
import org.openapitools.client.infrastructure.ApiResponse
import org.openapitools.client.infrastructure.ClientException
import org.openapitools.client.infrastructure.ClientError
import org.openapitools.client.infrastructure.ServerException
import org.openapitools.client.infrastructure.ServerError
import org.openapitools.client.infrastructure.MultiValueMap
import org.openapitools.client.infrastructure.PartConfig
import org.openapitools.client.infrastructure.RequestConfig
import org.openapitools.client.infrastructure.RequestMethod
import org.openapitools.client.infrastructure.ResponseType
import org.openapitools.client.infrastructure.Success
import org.openapitools.client.infrastructure.toMultiValue

class MediaApi(basePath: kotlin.String = defaultBasePath, client: OkHttpClient = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost")
        }
    }

    /**
     * Delete Media
     * 
     * @param mediaId 
     * @return ModelApiResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun deleteMediaApiV1MediaMediaIdDelete(mediaId: java.util.UUID) : ModelApiResponse {
        val localVarResponse = deleteMediaApiV1MediaMediaIdDeleteWithHttpInfo(mediaId = mediaId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ModelApiResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Delete Media
     * 
     * @param mediaId 
     * @return ApiResponse<ModelApiResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun deleteMediaApiV1MediaMediaIdDeleteWithHttpInfo(mediaId: java.util.UUID) : ApiResponse<ModelApiResponse?> {
        val localVariableConfig = deleteMediaApiV1MediaMediaIdDeleteRequestConfig(mediaId = mediaId)

        return request<Unit, ModelApiResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation deleteMediaApiV1MediaMediaIdDelete
     *
     * @param mediaId 
     * @return RequestConfig
     */
    fun deleteMediaApiV1MediaMediaIdDeleteRequestConfig(mediaId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/api/v1/media/{media_id}".replace("{"+"media_id"+"}", encodeURIComponent(mediaId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Get Media
     * 
     * @param mediaId 
     * @return ApiResponseMediaAssetDTO
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getMediaApiV1MediaMediaIdGet(mediaId: java.util.UUID) : ApiResponseMediaAssetDTO {
        val localVarResponse = getMediaApiV1MediaMediaIdGetWithHttpInfo(mediaId = mediaId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ApiResponseMediaAssetDTO
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Get Media
     * 
     * @param mediaId 
     * @return ApiResponse<ApiResponseMediaAssetDTO?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getMediaApiV1MediaMediaIdGetWithHttpInfo(mediaId: java.util.UUID) : ApiResponse<ApiResponseMediaAssetDTO?> {
        val localVariableConfig = getMediaApiV1MediaMediaIdGetRequestConfig(mediaId = mediaId)

        return request<Unit, ApiResponseMediaAssetDTO>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getMediaApiV1MediaMediaIdGet
     *
     * @param mediaId 
     * @return RequestConfig
     */
    fun getMediaApiV1MediaMediaIdGetRequestConfig(mediaId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/media/{media_id}".replace("{"+"media_id"+"}", encodeURIComponent(mediaId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Get Media For Entity
     *
     * @param entityType
     * @param entityId
     * @return ApiResponseListMediaAssetDTO
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getMediaForEntityApiV1MediaEntityEntityTypeEntityIdGet(entityType: MediaEntityType, entityId: java.util.UUID) : ApiResponseListMediaAssetDTO {
        val localVarResponse = getMediaForEntityApiV1MediaEntityEntityTypeEntityIdGetWithHttpInfo(entityType = entityType, entityId = entityId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ApiResponseListMediaAssetDTO
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Get Media For Entity
     *
     * @param entityType
     * @param entityId
     * @return ApiResponse<ApiResponseListMediaAssetDTO?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getMediaForEntityApiV1MediaEntityEntityTypeEntityIdGetWithHttpInfo(entityType: MediaEntityType, entityId: java.util.UUID) : ApiResponse<ApiResponseListMediaAssetDTO?> {
        val localVariableConfig = getMediaForEntityApiV1MediaEntityEntityTypeEntityIdGetRequestConfig(entityType = entityType, entityId = entityId)

        return request<Unit, ApiResponseListMediaAssetDTO>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getMediaForEntityApiV1MediaEntityEntityTypeEntityIdGet
     *
     * @param entityType
     * @param entityId
     * @return RequestConfig
     */
    fun getMediaForEntityApiV1MediaEntityEntityTypeEntityIdGetRequestConfig(entityType: MediaEntityType, entityId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/media/entity/{entity_type}/{entity_id}"
                .replace("{"+"entity_type"+"}", encodeURIComponent(entityType.toString()))
                .replace("{"+"entity_id"+"}", encodeURIComponent(entityId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * Search Media
     *
     * @param entityType  (optional)
     * @param entityId  (optional)
     * @param isPublic  (optional)
     * @param limit  (optional, default to 50)
     * @param offset  (optional, default to 0)
     * @return ApiResponsePageMediaAssetDTO
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun searchMediaApiV1MediaGet(entityType: MediaEntityType? = null, entityId: java.util.UUID? = null, isPublic: kotlin.Boolean? = null, limit: kotlin.Int? = 50, offset: kotlin.Int? = 0) : ApiResponsePageMediaAssetDTO {
        val localVarResponse = searchMediaApiV1MediaGetWithHttpInfo(entityType = entityType, entityId = entityId, isPublic = isPublic, limit = limit, offset = offset)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ApiResponsePageMediaAssetDTO
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Search Media
     * 
     * @param entityType  (optional)
     * @param entityId  (optional)
     * @param isPublic  (optional)
     * @param limit  (optional, default to 50)
     * @param offset  (optional, default to 0)
     * @return ApiResponse<ApiResponsePageMediaAssetDTO?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun searchMediaApiV1MediaGetWithHttpInfo(entityType: MediaEntityType?, entityId: java.util.UUID?, isPublic: kotlin.Boolean?, limit: kotlin.Int?, offset: kotlin.Int?) : ApiResponse<ApiResponsePageMediaAssetDTO?> {
        val localVariableConfig = searchMediaApiV1MediaGetRequestConfig(entityType = entityType, entityId = entityId, isPublic = isPublic, limit = limit, offset = offset)

        return request<Unit, ApiResponsePageMediaAssetDTO>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation searchMediaApiV1MediaGet
     *
     * @param entityType  (optional)
     * @param entityId  (optional)
     * @param isPublic  (optional)
     * @param limit  (optional, default to 50)
     * @param offset  (optional, default to 0)
     * @return RequestConfig
     */
    fun searchMediaApiV1MediaGetRequestConfig(entityType: MediaEntityType?, entityId: java.util.UUID?, isPublic: kotlin.Boolean?, limit: kotlin.Int?, offset: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (entityType != null) {
                    put("entity_type", listOf(entityType.toString()))
                }
                if (entityId != null) {
                    put("entity_id", listOf(entityId.toString()))
                }
                if (isPublic != null) {
                    put("is_public", listOf(isPublic.toString()))
                }
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (offset != null) {
                    put("offset", listOf(offset.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/media/",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Upload Media
     * 
     * @param file Image file (png/jpeg/webp/gif/bmp/tiff/ico)
     * @param entityType Owning entity kind: character | scene | user
     * @param entityId ID of the owning entity
     * @param isPublic Anonymous-readable (public bucket) or owner-only (presigned) (optional, default to false)
     * @return ApiResponseMediaAssetDTO
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun uploadMediaApiV1MediaPost(file: kotlin.String, entityType: MediaEntityType, entityId: java.util.UUID, isPublic: kotlin.Boolean? = false) : ApiResponseMediaAssetDTO {
        val localVarResponse = uploadMediaApiV1MediaPostWithHttpInfo(file = file, entityType = entityType, entityId = entityId, isPublic = isPublic)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ApiResponseMediaAssetDTO
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Upload Media
     * 
     * @param file Image file (png/jpeg/webp/gif/bmp/tiff/ico)
     * @param entityType Owning entity kind: character | scene | user
     * @param entityId ID of the owning entity
     * @param isPublic Anonymous-readable (public bucket) or owner-only (presigned) (optional, default to false)
     * @return ApiResponse<ApiResponseMediaAssetDTO?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun uploadMediaApiV1MediaPostWithHttpInfo(file: kotlin.String, entityType: MediaEntityType, entityId: java.util.UUID, isPublic: kotlin.Boolean?) : ApiResponse<ApiResponseMediaAssetDTO?> {
        val localVariableConfig = uploadMediaApiV1MediaPostRequestConfig(file = file, entityType = entityType, entityId = entityId, isPublic = isPublic)

        return request<Map<String, PartConfig<*>>, ApiResponseMediaAssetDTO>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation uploadMediaApiV1MediaPost
     *
     * @param file Image file (png/jpeg/webp/gif/bmp/tiff/ico)
     * @param entityType Owning entity kind: character | scene | user
     * @param entityId ID of the owning entity
     * @param isPublic Anonymous-readable (public bucket) or owner-only (presigned) (optional, default to false)
     * @return RequestConfig
     */
    fun uploadMediaApiV1MediaPostRequestConfig(file: kotlin.String, entityType: MediaEntityType, entityId: java.util.UUID, isPublic: kotlin.Boolean?) : RequestConfig<Map<String, PartConfig<*>>> {
        val localVariableBody = mapOf(
            "file" to PartConfig(body = file, headers = mutableMapOf()),
            "entity_type" to PartConfig(body = entityType, headers = mutableMapOf()),
            "entity_id" to PartConfig(body = entityId, headers = mutableMapOf()),
            "is_public" to PartConfig(body = isPublic, headers = mutableMapOf()),)
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf("Content-Type" to "multipart/form-data")
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/media/",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
