/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import java.io.IOException
import okhttp3.OkHttpClient
import okhttp3.HttpUrl

import org.openapitools.client.models.ApiResponseMessage
import org.openapitools.client.models.ApiResponsePageMessage
import org.openapitools.client.models.BodyUpdateMessageApiV1MessagesMessageIdPut
import org.openapitools.client.models.ChatRoles
import org.openapitools.client.models.HTTPValidationError
import org.openapitools.client.models.ModelApiResponse
import org.openapitools.client.models.SendMessageRequest

import com.squareup.moshi.Json

import org.openapitools.client.infrastructure.ApiClient
import org.openapitools.client.infrastructure.ApiResponse
import org.openapitools.client.infrastructure.ClientException
import org.openapitools.client.infrastructure.ClientError
import org.openapitools.client.infrastructure.ServerException
import org.openapitools.client.infrastructure.ServerError
import org.openapitools.client.infrastructure.MultiValueMap
import org.openapitools.client.infrastructure.PartConfig
import org.openapitools.client.infrastructure.RequestConfig
import org.openapitools.client.infrastructure.RequestMethod
import org.openapitools.client.infrastructure.ResponseType
import org.openapitools.client.infrastructure.Success
import org.openapitools.client.infrastructure.toMultiValue

class MessagesApi(basePath: kotlin.String = defaultBasePath, client: OkHttpClient = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost")
        }
    }

    /**
     * Create Message
     * 
     * @param sendMessageRequest 
     * @return ApiResponseMessage
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createMessageApiV1MessagesPost(sendMessageRequest: SendMessageRequest) : ApiResponseMessage {
        val localVarResponse = createMessageApiV1MessagesPostWithHttpInfo(sendMessageRequest = sendMessageRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ApiResponseMessage
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Create Message
     * 
     * @param sendMessageRequest 
     * @return ApiResponse<ApiResponseMessage?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun createMessageApiV1MessagesPostWithHttpInfo(sendMessageRequest: SendMessageRequest) : ApiResponse<ApiResponseMessage?> {
        val localVariableConfig = createMessageApiV1MessagesPostRequestConfig(sendMessageRequest = sendMessageRequest)

        return request<SendMessageRequest, ApiResponseMessage>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createMessageApiV1MessagesPost
     *
     * @param sendMessageRequest 
     * @return RequestConfig
     */
    fun createMessageApiV1MessagesPostRequestConfig(sendMessageRequest: SendMessageRequest) : RequestConfig<SendMessageRequest> {
        val localVariableBody = sendMessageRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/messages/",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Delete Message
     * 
     * @param messageId 
     * @return ModelApiResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun deleteMessageApiV1MessagesMessageIdDelete(messageId: java.util.UUID) : ModelApiResponse {
        val localVarResponse = deleteMessageApiV1MessagesMessageIdDeleteWithHttpInfo(messageId = messageId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ModelApiResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Delete Message
     * 
     * @param messageId 
     * @return ApiResponse<ModelApiResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun deleteMessageApiV1MessagesMessageIdDeleteWithHttpInfo(messageId: java.util.UUID) : ApiResponse<ModelApiResponse?> {
        val localVariableConfig = deleteMessageApiV1MessagesMessageIdDeleteRequestConfig(messageId = messageId)

        return request<Unit, ModelApiResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation deleteMessageApiV1MessagesMessageIdDelete
     *
     * @param messageId 
     * @return RequestConfig
     */
    fun deleteMessageApiV1MessagesMessageIdDeleteRequestConfig(messageId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/api/v1/messages/{message_id}".replace("{"+"message_id"+"}", encodeURIComponent(messageId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Get Message Details
     * 
     * @param messageId 
     * @return ApiResponseMessage
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getMessageDetailsApiV1MessagesMessageIdGet(messageId: java.util.UUID) : ApiResponseMessage {
        val localVarResponse = getMessageDetailsApiV1MessagesMessageIdGetWithHttpInfo(messageId = messageId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ApiResponseMessage
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Get Message Details
     * 
     * @param messageId 
     * @return ApiResponse<ApiResponseMessage?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getMessageDetailsApiV1MessagesMessageIdGetWithHttpInfo(messageId: java.util.UUID) : ApiResponse<ApiResponseMessage?> {
        val localVariableConfig = getMessageDetailsApiV1MessagesMessageIdGetRequestConfig(messageId = messageId)

        return request<Unit, ApiResponseMessage>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getMessageDetailsApiV1MessagesMessageIdGet
     *
     * @param messageId 
     * @return RequestConfig
     */
    fun getMessageDetailsApiV1MessagesMessageIdGetRequestConfig(messageId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/messages/{message_id}".replace("{"+"message_id"+"}", encodeURIComponent(messageId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Search Messages
     * 
     * @param ids  (optional)
     * @param chatsIds  (optional)
     * @param roles  (optional)
     * @param limit  (optional, default to 50)
     * @param offset  (optional, default to 0)
     * @return ApiResponsePageMessage
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun searchMessagesApiV1MessagesGet(ids: kotlin.collections.List<java.util.UUID>? = null, chatsIds: kotlin.collections.List<java.util.UUID>? = null, roles: kotlin.collections.List<ChatRoles>? = null, limit: kotlin.Int? = 50, offset: kotlin.Int? = 0) : ApiResponsePageMessage {
        val localVarResponse = searchMessagesApiV1MessagesGetWithHttpInfo(ids = ids, chatsIds = chatsIds, roles = roles, limit = limit, offset = offset)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ApiResponsePageMessage
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Search Messages
     * 
     * @param ids  (optional)
     * @param chatsIds  (optional)
     * @param roles  (optional)
     * @param limit  (optional, default to 50)
     * @param offset  (optional, default to 0)
     * @return ApiResponse<ApiResponsePageMessage?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun searchMessagesApiV1MessagesGetWithHttpInfo(ids: kotlin.collections.List<java.util.UUID>?, chatsIds: kotlin.collections.List<java.util.UUID>?, roles: kotlin.collections.List<ChatRoles>?, limit: kotlin.Int?, offset: kotlin.Int?) : ApiResponse<ApiResponsePageMessage?> {
        val localVariableConfig = searchMessagesApiV1MessagesGetRequestConfig(ids = ids, chatsIds = chatsIds, roles = roles, limit = limit, offset = offset)

        return request<Unit, ApiResponsePageMessage>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation searchMessagesApiV1MessagesGet
     *
     * @param ids  (optional)
     * @param chatsIds  (optional)
     * @param roles  (optional)
     * @param limit  (optional, default to 50)
     * @param offset  (optional, default to 0)
     * @return RequestConfig
     */
    fun searchMessagesApiV1MessagesGetRequestConfig(ids: kotlin.collections.List<java.util.UUID>?, chatsIds: kotlin.collections.List<java.util.UUID>?, roles: kotlin.collections.List<ChatRoles>?, limit: kotlin.Int?, offset: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (ids != null) {
                    put("ids", toMultiValue(ids.toList(), "multi"))
                }
                if (chatsIds != null) {
                    put("chats_ids", toMultiValue(chatsIds.toList(), "multi"))
                }
                if (roles != null) {
                    put("roles", toMultiValue(roles.toList(), "multi"))
                }
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (offset != null) {
                    put("offset", listOf(offset.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/messages/",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Update Message
     * 
     * @param messageId 
     * @param bodyUpdateMessageApiV1MessagesMessageIdPut 
     * @return ModelApiResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun updateMessageApiV1MessagesMessageIdPut(messageId: java.util.UUID, bodyUpdateMessageApiV1MessagesMessageIdPut: BodyUpdateMessageApiV1MessagesMessageIdPut) : ModelApiResponse {
        val localVarResponse = updateMessageApiV1MessagesMessageIdPutWithHttpInfo(messageId = messageId, bodyUpdateMessageApiV1MessagesMessageIdPut = bodyUpdateMessageApiV1MessagesMessageIdPut)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ModelApiResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Update Message
     * 
     * @param messageId 
     * @param bodyUpdateMessageApiV1MessagesMessageIdPut 
     * @return ApiResponse<ModelApiResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun updateMessageApiV1MessagesMessageIdPutWithHttpInfo(messageId: java.util.UUID, bodyUpdateMessageApiV1MessagesMessageIdPut: BodyUpdateMessageApiV1MessagesMessageIdPut) : ApiResponse<ModelApiResponse?> {
        val localVariableConfig = updateMessageApiV1MessagesMessageIdPutRequestConfig(messageId = messageId, bodyUpdateMessageApiV1MessagesMessageIdPut = bodyUpdateMessageApiV1MessagesMessageIdPut)

        return request<BodyUpdateMessageApiV1MessagesMessageIdPut, ModelApiResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation updateMessageApiV1MessagesMessageIdPut
     *
     * @param messageId 
     * @param bodyUpdateMessageApiV1MessagesMessageIdPut 
     * @return RequestConfig
     */
    fun updateMessageApiV1MessagesMessageIdPutRequestConfig(messageId: java.util.UUID, bodyUpdateMessageApiV1MessagesMessageIdPut: BodyUpdateMessageApiV1MessagesMessageIdPut) : RequestConfig<BodyUpdateMessageApiV1MessagesMessageIdPut> {
        val localVariableBody = bodyUpdateMessageApiV1MessagesMessageIdPut
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/api/v1/messages/{message_id}".replace("{"+"message_id"+"}", encodeURIComponent(messageId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
