/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import java.io.IOException
import okhttp3.OkHttpClient
import okhttp3.HttpUrl

import org.openapitools.client.models.ApiResponseDict
import org.openapitools.client.models.ApiResponsePageUser
import org.openapitools.client.models.HTTPValidationError
import org.openapitools.client.models.UserRole

import com.squareup.moshi.Json

import org.openapitools.client.infrastructure.ApiClient
import org.openapitools.client.infrastructure.ApiResponse
import org.openapitools.client.infrastructure.ClientException
import org.openapitools.client.infrastructure.ClientError
import org.openapitools.client.infrastructure.ServerException
import org.openapitools.client.infrastructure.ServerError
import org.openapitools.client.infrastructure.MultiValueMap
import org.openapitools.client.infrastructure.PartConfig
import org.openapitools.client.infrastructure.RequestConfig
import org.openapitools.client.infrastructure.RequestMethod
import org.openapitools.client.infrastructure.ResponseType
import org.openapitools.client.infrastructure.Success
import org.openapitools.client.infrastructure.toMultiValue

class UsersApi(basePath: kotlin.String = defaultBasePath, client: OkHttpClient = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost")
        }
    }

    /**
     * Delete User
     * 
     * @param userId 
     * @return ApiResponseDict
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun deleteUserUsersUserIdDelete(userId: java.util.UUID) : ApiResponseDict {
        val localVarResponse = deleteUserUsersUserIdDeleteWithHttpInfo(userId = userId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ApiResponseDict
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Delete User
     * 
     * @param userId 
     * @return ApiResponse<ApiResponseDict?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun deleteUserUsersUserIdDeleteWithHttpInfo(userId: java.util.UUID) : ApiResponse<ApiResponseDict?> {
        val localVariableConfig = deleteUserUsersUserIdDeleteRequestConfig(userId = userId)

        return request<Unit, ApiResponseDict>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation deleteUserUsersUserIdDelete
     *
     * @param userId 
     * @return RequestConfig
     */
    fun deleteUserUsersUserIdDeleteRequestConfig(userId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/users/{user_id}".replace("{"+"user_id"+"}", encodeURIComponent(userId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Search Users
     * 
     * @param userIds  (optional)
     * @param usernames  (optional)
     * @param googleIds  (optional)
     * @param roles  (optional)
     * @param limit  (optional)
     * @param offset  (optional)
     * @return ApiResponsePageUser
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun searchUsersUsersSearchGet(userIds: kotlin.collections.List<java.util.UUID>? = null, usernames: kotlin.collections.List<kotlin.String>? = null, googleIds: kotlin.collections.List<kotlin.String>? = null, roles: kotlin.collections.List<UserRole>? = null, limit: kotlin.Int? = null, offset: kotlin.Int? = null) : ApiResponsePageUser {
        val localVarResponse = searchUsersUsersSearchGetWithHttpInfo(userIds = userIds, usernames = usernames, googleIds = googleIds, roles = roles, limit = limit, offset = offset)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ApiResponsePageUser
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Search Users
     * 
     * @param userIds  (optional)
     * @param usernames  (optional)
     * @param googleIds  (optional)
     * @param roles  (optional)
     * @param limit  (optional)
     * @param offset  (optional)
     * @return ApiResponse<ApiResponsePageUser?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun searchUsersUsersSearchGetWithHttpInfo(userIds: kotlin.collections.List<java.util.UUID>?, usernames: kotlin.collections.List<kotlin.String>?, googleIds: kotlin.collections.List<kotlin.String>?, roles: kotlin.collections.List<UserRole>?, limit: kotlin.Int?, offset: kotlin.Int?) : ApiResponse<ApiResponsePageUser?> {
        val localVariableConfig = searchUsersUsersSearchGetRequestConfig(userIds = userIds, usernames = usernames, googleIds = googleIds, roles = roles, limit = limit, offset = offset)

        return request<Unit, ApiResponsePageUser>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation searchUsersUsersSearchGet
     *
     * @param userIds  (optional)
     * @param usernames  (optional)
     * @param googleIds  (optional)
     * @param roles  (optional)
     * @param limit  (optional)
     * @param offset  (optional)
     * @return RequestConfig
     */
    fun searchUsersUsersSearchGetRequestConfig(userIds: kotlin.collections.List<java.util.UUID>?, usernames: kotlin.collections.List<kotlin.String>?, googleIds: kotlin.collections.List<kotlin.String>?, roles: kotlin.collections.List<UserRole>?, limit: kotlin.Int?, offset: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (userIds != null) {
                    put("user_ids", toMultiValue(userIds.toList(), "multi"))
                }
                if (usernames != null) {
                    put("usernames", toMultiValue(usernames.toList(), "multi"))
                }
                if (googleIds != null) {
                    put("google_ids", toMultiValue(googleIds.toList(), "multi"))
                }
                if (roles != null) {
                    put("roles", toMultiValue(roles.toList(), "multi"))
                }
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (offset != null) {
                    put("offset", listOf(offset.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/users/search",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
