/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.MediaAssetDTO

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 * @param result
 * @param correlationId
 */


data class ApiResponseListMediaAssetDTO (

    @Json(name = "result")
    val result: kotlin.collections.List<MediaAssetDTO>,

    @Json(name = "correlation_id")
    val correlationId: kotlin.String? = null

) {


}
