/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Character ids to add to a scene's roster after it exists (e.g. mid-chat).
 *
 * @param characterIds 
 */


data class AttachCharactersDTO (

    @Json(name = "character_ids")
    val characterIds: kotlin.collections.List<java.util.UUID>

) {


}

