/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Whether the requesting user has bookmarked an entity.
 *
 * @param bookmarked 
 */


data class BookmarkState (

    @Json(name = "bookmarked")
    val bookmarked: kotlin.Boolean

) {


}

