/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name 
 * @param systemPrompt 
 * @param id 
 * @param ownerId 
 * @param isPublic 
 */


data class Character (

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "system_prompt")
    val systemPrompt: kotlin.String,

    @Json(name = "id")
    val id: java.util.UUID? = null,

    @Json(name = "owner_id")
    val ownerId: java.util.UUID? = null,

    @Json(name = "is_public")
    val isPublic: kotlin.Boolean? = false

) {


}

