/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ControlBehavior
import org.openapitools.client.models.FunctionsSettings
import org.openapitools.client.models.Perspective
import org.openapitools.client.models.ReasoningEffort
import org.openapitools.client.models.ResponseLength
import org.openapitools.client.models.TemperatureSettings
import org.openapitools.client.models.Toggle
import org.openapitools.client.models.TokenLimit

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param aiControlBehavior 
 * @param continueBehavior 
 * @param perspective 
 * @param temperature 
 * @param responseLength 
 * @param responseTokenLimit Max token limit. 2k tokens noted in UI.
 * @param reasoning 
 * @param reasoningEffort 
 * @param aiMediaPicker 
 * @param functions 
 * @param contextLimitOverride 
 */


data class ChatSettings (

    @Json(name = "aiControlBehavior")
    val aiControlBehavior: ControlBehavior,

    @Json(name = "continueBehavior")
    val continueBehavior: ControlBehavior,

    @Json(name = "perspective")
    val perspective: Perspective,

    @Json(name = "temperature")
    val temperature: TemperatureSettings,

    @Json(name = "responseLength")
    val responseLength: ResponseLength,

    /* Max token limit. 2k tokens noted in UI. */
    @Json(name = "responseTokenLimit")
    val responseTokenLimit: TokenLimit,

    @Json(name = "reasoning")
    val reasoning: Toggle,

    @Json(name = "reasoningEffort")
    val reasoningEffort: ReasoningEffort,

    @Json(name = "aiMediaPicker")
    val aiMediaPicker: Toggle,

    @Json(name = "functions")
    val functions: FunctionsSettings,

    @Json(name = "contextLimitOverride")
    val contextLimitOverride: kotlin.Int? = null

) {


}

