/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param title 
 * @param userId 
 * @param sceneId 
 * @param id 
 */


data class Chat (

    @Json(name = "title")
    val title: kotlin.String,

    @Json(name = "user_id")
    val userId: java.util.UUID,

    @Json(name = "scene_id")
    val sceneId: java.util.UUID,

    @Json(name = "id")
    val id: java.util.UUID? = null

) {


}

