/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ModelContextUsage

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param cardsTokens 
 * @param historyTokens 
 * @param historyMessagesCount 
 * @param totalTokens 
 * @param estimated 
 * @param models 
 */


data class ContextUsage (

    @Json(name = "cards_tokens")
    val cardsTokens: kotlin.Int,

    @Json(name = "history_tokens")
    val historyTokens: kotlin.Int,

    @Json(name = "history_messages_count")
    val historyMessagesCount: kotlin.Int,

    @Json(name = "total_tokens")
    val totalTokens: kotlin.Int,

    @Json(name = "estimated")
    val estimated: kotlin.Boolean,

    @Json(name = "models")
    val models: kotlin.collections.List<ModelContextUsage>

) {


}

