/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param characterNameGenerator Generates unique character names using AI
 */


data class FunctionsSettings (

    /* Generates unique character names using AI */
    @Json(name = "characterNameGenerator")
    val characterNameGenerator: kotlin.Boolean? = true

) {


}

