/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param charactersCreated 
 * @param scenesCreated 
 * @param imagesImported 
 * @param imageFailures 
 * @param characterIds 
 * @param sceneIds 
 * @param skippedEntries
 * @param appendedToCharacterId Set when the lorebook was appended to an existing character instead of
 *     creating new entities.
 */


data class ImportLorebookResultDTO (

    @Json(name = "characters_created")
    val charactersCreated: kotlin.Int,

    @Json(name = "scenes_created")
    val scenesCreated: kotlin.Int,

    @Json(name = "images_imported")
    val imagesImported: kotlin.Int,

    @Json(name = "image_failures")
    val imageFailures: kotlin.collections.List<kotlin.String>,

    @Json(name = "character_ids")
    val characterIds: kotlin.collections.List<java.util.UUID>,

    @Json(name = "scene_ids")
    val sceneIds: kotlin.collections.List<java.util.UUID>,

    @Json(name = "skipped_entries")
    val skippedEntries: kotlin.Int,

    @Json(name = "appended_to_character_id")
    val appendedToCharacterId: java.util.UUID? = null

) {


}

