/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ImportCandidateDTO

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Result of a parse-only preview: no DB writes, just the candidates.
 *
 * @param characters 
 * @param scenes 
 * @param otherEntries 
 * @param skippedEntries 
 * @param worldContextPreview 
 */


data class ImportPreviewDTO (

    @Json(name = "characters")
    val characters: kotlin.collections.List<ImportCandidateDTO>,

    @Json(name = "scenes")
    val scenes: kotlin.collections.List<ImportCandidateDTO>,

    @Json(name = "other_entries")
    val otherEntries: kotlin.Int,

    @Json(name = "skipped_entries")
    val skippedEntries: kotlin.Int,

    @Json(name = "world_context_preview")
    val worldContextPreview: kotlin.String

) {


}

