/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Uid

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * One selectable entry discovered while previewing a lorebook.  ``key`` is the stable handle the client sends back to import this entry; the other fields are display-only so the user can decide what to keep.
 *
 * @param key 
 * @param uid 
 * @param name 
 * @param group 
 * @param contentPreview 
 * @param contentLength 
 * @param imageCount 
 */


data class ImportCandidateDTO (

    @Json(name = "key")
    val key: kotlin.String,

    @Json(name = "uid")
    val uid: Uid?,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "group")
    val group: kotlin.String,

    @Json(name = "content_preview")
    val contentPreview: kotlin.String,

    @Json(name = "content_length")
    val contentLength: kotlin.Int,

    @Json(name = "image_count")
    val imageCount: kotlin.Int

) {


}

