/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param text 
 * @param id 
 * @param sceneId 
 * @param dateCreated 
 * @param dateEdited 
 */


data class InitialMessage (

    @Json(name = "text")
    val text: kotlin.String,

    @Json(name = "id")
    val id: java.util.UUID? = null,

    @Json(name = "scene_id")
    val sceneId: java.util.UUID? = null,

    @Json(name = "date_created")
    val dateCreated: java.time.OffsetDateTime? = null,

    @Json(name = "date_edited")
    val dateEdited: java.time.OffsetDateTime? = null

) {


}

