/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Like state of an entity for the requesting user plus its total like count.
 *
 * @param liked 
 * @param likesCount 
 */


data class LikeState (

    @Json(name = "liked")
    val liked: kotlin.Boolean,

    @Json(name = "likes_count")
    val likesCount: kotlin.Int

) {


}

