/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: testing_mock,geminiMinus3MinusFlashMinusPreview,geminiMinus3Period1MinusProMinusPreview,claudeMinusSonnetMinus4Minus20250514,claudeMinusHaikuMinus4Minus20250514,qwenMinusPlus,qwenMinusTurbo,qwenMinusMax,glmMinus5Period2,glmMinus4Period6,glmMinus4Period5
 */

@JsonClass(generateAdapter = false)
enum class LLMModelType(val value: kotlin.String) {

    @Json(name = "testing_mock")
    testing_mock("testing_mock"),

    @Json(name = "gemini-3-flash-preview")
    geminiMinus3MinusFlashMinusPreview("gemini-3-flash-preview"),

    @Json(name = "gemini-3.1-pro-preview")
    geminiMinus3Period1MinusProMinusPreview("gemini-3.1-pro-preview"),

    @Json(name = "claude-sonnet-4-20250514")
    claudeMinusSonnetMinus4Minus20250514("claude-sonnet-4-20250514"),

    @Json(name = "claude-haiku-4-20250514")
    claudeMinusHaikuMinus4Minus20250514("claude-haiku-4-20250514"),

    @Json(name = "qwen-plus")
    qwenMinusPlus("qwen-plus"),

    @Json(name = "qwen-turbo")
    qwenMinusTurbo("qwen-turbo"),

    @Json(name = "qwen-max")
    qwenMinusMax("qwen-max"),

    @Json(name = "glm-5.2")
    glmMinus5Period2("glm-5.2"),

    @Json(name = "glm-4.6")
    glmMinus4Period6("glm-4.6"),

    @Json(name = "glm-4.5")
    glmMinus4Period5("glm-4.5");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is LLMModelType) "$data" else null

        /**
         * Returns a valid [LLMModelType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): LLMModelType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

