/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The kind of entity a media asset (image) is attached to.
 *
 * Values: character,scene,user
 */

@JsonClass(generateAdapter = false)
enum class MediaEntityType(val value: kotlin.String) {

    @Json(name = "character")
    character("character"),

    @Json(name = "scene")
    scene("scene"),

    @Json(name = "user")
    user("user");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is MediaEntityType) "$data" else null

        /**
         * Returns a valid [MediaEntityType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): MediaEntityType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

