/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.MediaEntityType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Client-facing representation of a media asset.  ``url`` is computed by the service: a stable public URL for public assets, a short-lived presigned URL for private assets, or the legacy ``file_url`` as-is for assets that still point at an external location. The object key / bucket are intentionally NOT exposed.
 *
 * @param id 
 * @param url 
 * @param contentType 
 * @param sizeBytes 
 * @param entityType 
 * @param entityId 
 * @param isPublic 
 * @param createdAt 
 */


data class MediaAssetDTO (

    @Json(name = "id")
    val id: java.util.UUID,

    @Json(name = "url")
    val url: kotlin.String,

    @Json(name = "content_type")
    val contentType: kotlin.String,

    @Json(name = "size_bytes")
    val sizeBytes: kotlin.Int,

    @Json(name = "entity_type")
    val entityType: MediaEntityType,

    @Json(name = "entity_id")
    val entityId: java.util.UUID,

    @Json(name = "is_public")
    val isPublic: kotlin.Boolean,

    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime? = null

) {


}

