/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.MediaLayer

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param sortOrder 
 * @param caption 
 * @param layer 
 */


data class MediaUpdateDTO (

    @Json(name = "sort_order")
    val sortOrder: kotlin.Int? = null,

    @Json(name = "caption")
    val caption: kotlin.String? = null,

    @Json(name = "layer")
    val layer: MediaLayer? = null

) {


}

