/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.MediaEntityType
import org.openapitools.client.models.MediaLayer

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param id
 * @param url
 * @param contentType
 * @param sizeBytes
 * @param entityType
 * @param entityId
 * @param isPublic
 * @param sortOrder
 * @param caption
 * @param layer
 * @param createdAt
 */


data class MediaAssetDTO (

    @Json(name = "id")
    val id: java.util.UUID,

    @Json(name = "url")
    val url: kotlin.String,

    @Json(name = "content_type")
    val contentType: kotlin.String,

    @Json(name = "size_bytes")
    val sizeBytes: kotlin.Int,

    @Json(name = "entity_type")
    val entityType: MediaEntityType,

    @Json(name = "entity_id")
    val entityId: java.util.UUID,

    @Json(name = "is_public")
    val isPublic: kotlin.Boolean,

    @Json(name = "sort_order")
    val sortOrder: kotlin.Int? = 0,

    @Json(name = "caption")
    val caption: kotlin.String? = null,

    @Json(name = "layer")
    val layer: MediaLayer? = null,

    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime? = null

) {


}

