/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ChatRoles
import org.openapitools.client.models.MessageStatus

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param message 
 * @param chatId 
 * @param role 
 * @param id 
 * @param status 
 * @param dateCreated 
 * @param dateEdited 
 * @param reasoning 
 */


data class Message (

    @Json(name = "message")
    val message: kotlin.String,

    @Json(name = "chat_id")
    val chatId: java.util.UUID,

    @Json(name = "role")
    val role: ChatRoles,

    @Json(name = "id")
    val id: java.util.UUID? = null,

    @Json(name = "status")
    val status: MessageStatus? = null,

    @Json(name = "date_created")
    val dateCreated: java.time.OffsetDateTime? = null,

    @Json(name = "date_edited")
    val dateEdited: java.time.OffsetDateTime? = null,

    @Json(name = "reasoning")
    val reasoning: kotlin.String? = null

) {


}

