/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.LLMModelType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param llmModel 
 * @param contextWindowTokens 
 * @param remainingTokens 
 * @param fits 
 */


data class ModelContextUsage (

    @Json(name = "llm_model")
    val llmModel: LLMModelType,

    @Json(name = "context_window_tokens")
    val contextWindowTokens: kotlin.Int,

    @Json(name = "remaining_tokens")
    val remainingTokens: kotlin.Int,

    @Json(name = "fits")
    val fits: kotlin.Boolean

) {


}

