/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Message

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param items 
 * @param count 
 * @param offset 
 * @param limit 
 */


data class PageMessage (

    @Json(name = "items")
    val items: kotlin.collections.List<Message>,

    @Json(name = "count")
    val count: kotlin.Int,

    @Json(name = "offset")
    val offset: kotlin.Int,

    @Json(name = "limit")
    val limit: kotlin.Int

) {


}

