/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: _1st_Person,_2nd_Person,_3rd_Person
 */

@JsonClass(generateAdapter = false)
enum class Perspective(val value: kotlin.String) {

    @Json(name = "1st Person")
    _1st_Person("1st Person"),

    @Json(name = "2nd Person")
    _2nd_Person("2nd Person"),

    @Json(name = "3rd Person")
    _3rd_Person("3rd Person");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is Perspective) "$data" else null

        /**
         * Returns a valid [Perspective] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): Perspective? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

