/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param ownerId 
 * @param title 
 * @param backgroundPrompt 
 * @param initialMessageText 
 * @param id 
 * @param description 
 */


data class Scene (

    @Json(name = "owner_id")
    val ownerId: java.util.UUID,

    @Json(name = "title")
    val title: kotlin.String,

    @Json(name = "background_prompt")
    val backgroundPrompt: kotlin.String,

    @Json(name = "initial_message_text")
    val initialMessageText: kotlin.String,

    @Json(name = "id")
    val id: java.util.UUID? = null,

    @Json(name = "description")
    val description: kotlin.String? = null

) {


}

