/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.LLMModelType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param chatId 
 * @param message 
 * @param llmModel 
 */


data class SendMessageRequest (

    @Json(name = "chat_id")
    val chatId: java.util.UUID,

    @Json(name = "message")
    val message: kotlin.String,

    @Json(name = "llm_model")
    val llmModel: LLMModelType? = null

) : kotlin.collections.HashMap<String, kotlin.Any>() {


}

