/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Preset

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param preset 
 * @param `value` Controls AI creativity
 */


data class TemperatureSettings (

    @Json(name = "preset")
    val preset: Preset,

    /* Controls AI creativity */
    @Json(name = "value")
    val `value`: java.math.BigDecimal

) {


}

