/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 */


// 7.7.0 emits an empty `data class Uid()` for the `uid: string|int|null`
// anyOf on ImportCandidateDTO. An empty data class can't hold a value, so Moshi
// would fail to deserialize a scalar uid (and break the whole preview response).
// Mirror the ValidationErrorLocInner fix: alias to kotlin.Any so Moshi's built-in
// adapter reads the scalar (string or int) as-is. Selection uses `key`, not uid.
typealias Uid = kotlin.Any

