/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Character
import org.openapitools.client.models.Chat
import org.openapitools.client.models.Scene
import org.openapitools.client.models.UserRole

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param role 
 * @param id 
 * @param username 
 * @param googleId 
 * @param crystalBalance 
 * @param characters 
 * @param scenes 
 * @param chats 
 */


data class User (

    @Json(name = "role")
    val role: UserRole,

    @Json(name = "id")
    val id: java.util.UUID? = null,

    @Json(name = "username")
    val username: kotlin.String? = null,

    @Json(name = "google_id")
    val googleId: kotlin.String? = null,

    @Json(name = "crystal_balance")
    val crystalBalance: kotlin.Int? = 1000,

    @Json(name = "characters")
    val characters: kotlin.collections.List<Character>? = null,

    @Json(name = "scenes")
    val scenes: kotlin.collections.List<Scene>? = null,

    @Json(name = "chats")
    val chats: kotlin.collections.List<Chat>? = null

) {


}

