/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents an element in the `loc` array of a validation error.
 * Each element can be either a string or an integer.
 *
 * @param value The location element value (string or integer).
 */

@JsonClass(generateAdapter = false)
data class ValidationErrorLocInner (

    @Json(name = "value")
    val value: kotlin.Any? = null

) {

    companion object {
        fun fromString(s: String): ValidationErrorLocInner = ValidationErrorLocInner(value = s)
        fun fromInt(i: Int): ValidationErrorLocInner = ValidationErrorLocInner(value = i)
    }
}

